# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Ce bug a été automatiquement marqué comme étant en sursis car il n'a pas
  reçu d'activité depuis 60 jours. Il sera fermé si aucune activité n'est détectée
  dans les 7 prochains jours. Merci de votre compréhension.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Ce bug a été automatiquement clos car aucune activité n'a été enregistrée
  depuis 7 jours alors qu'il était marqué en sursis. Merci de votre compréhension.
